COMMON_TICKERS = {
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "GOOGL": "Alphabet Inc.",
    "AMZN": "Amazon.com Inc.",
    "META": "Meta Platforms Inc.",
    "TSLA": "Tesla Inc.",
    "NVDA": "NVIDIA Corporation",
    "JPM": "JPMorgan Chase & Co.",
    "V": "Visa Inc.",
    "JNJ": "Johnson & Johnson",
    "WMT": "Walmart Inc.",
    "PG": "Procter & Gamble Co.",
    "MA": "Mastercard Inc.",
    "UNH": "UnitedHealth Group",
    "HD": "Home Depot Inc.",
    "DIS": "Walt Disney Co.",
    "BAC": "Bank of America Corp",
    "XOM": "Exxon Mobil Corp",
    "CSCO": "Cisco Systems Inc.",
    "NFLX": "Netflix Inc.",
    "INTC": "Intel Corporation",
    "CRM": "Salesforce Inc.",
    "PFE": "Pfizer Inc.",
    "ABT": "Abbott Laboratories",
    "KO": "Coca-Cola Co.",
    "PEP": "PepsiCo Inc.",
    "NKE": "Nike Inc.",
    "MRK": "Merck & Co.",
    "T": "AT&T Inc.",
    "VZ": "Verizon Communications",
    "ADBE": "Adobe Inc.",
    "PYPL": "PayPal Holdings",
    "CMCSA": "Comcast Corporation",
    "ACN": "Accenture plc",
    "AVGO": "Broadcom Inc.",
    "TXN": "Texas Instruments",
    "QCOM": "Qualcomm Inc.",
    "COST": "Costco Wholesale",
    "AMD": "Advanced Micro Devices",
    "GILD": "Gilead Sciences",
    "TMO": "Thermo Fisher Scientific",
    "MCD": "McDonald's Corporation",
    "COP": "ConocoPhillips",
    "WFC": "Wells Fargo & Co.",
    "BMY": "Bristol-Myers Squibb",
    "NEE": "NextEra Energy",
    "PM": "Philip Morris International",
    "UPS": "United Parcel Service",
    "RTX": "RTX Corporation",
    "HON": "Honeywell International",
    "LOW": "Lowe's Companies",
    "ORCL": "Oracle Corporation",
    "SBUX": "Starbucks Corporation",
    "IBM": "IBM Corporation",
    "BA": "Boeing Company",
    "GS": "Goldman Sachs Group",
    "CAT": "Caterpillar Inc.",
    "MDLZ": "Mondelez International",
    "DE": "Deere & Company",
    "BLK": "BlackRock Inc.",
    "AXP": "American Express",
    "SYK": "Stryker Corporation",
    "ISRG": "Intuitive Surgical",
    "PLD": "Prologis Inc.",
    "ADI": "Analog Devices",
    "MMC": "Marsh & McLennan",
    "CME": "CME Group Inc.",
    "SCHW": "Charles Schwab Corp",
    "CB": "Chubb Limited",
    "SO": "Southern Company",
    "CI": "Cigna Group",
    "DUK": "Duke Energy",
    "PGR": "Progressive Corporation",
    "CL": "Colgate-Palmolive",
    "FDX": "FedEx Corporation",
    "USB": "U.S. Bancorp",
    "TGT": "Target Corporation",
    "EOG": "EOG Resources",
    "NSC": "Norfolk Southern",
    "PNC": "PNC Financial Services",
    "TFC": "Truist Financial",
    "REGN": "Regeneron Pharmaceuticals",
    "SLB": "Schlumberger NV",
    "WM": "Waste Management",
    "BDX": "Becton Dickinson",
    "ICE": "Intercontinental Exchange",
    "SHW": "Sherwin-Williams",
    "MCK": "McKesson Corporation",
    "ZTS": "Zoetis Inc.",
    "NOC": "Northrop Grumman",
    "GD": "General Dynamics",
    "EMR": "Emerson Electric",
    "F": "Ford Motor Company",
    "GM": "General Motors",
    "TSM": "Taiwan Semiconductor",
    "SONY": "Sony Group Corporation",
    "NIO": "NIO Inc.",
    "SNAP": "Snap Inc.",
    "UBER": "Uber Technologies",
    "ABNB": "Airbnb Inc.",
    "COIN": "Coinbase Global",
    "SQ": "Block Inc.",
    "RIVN": "Rivian Automotive",
    "PLTR": "Palantir Technologies",
    "SOFI": "SoFi Technologies",
    "DKNG": "DraftKings Inc.",
    "ROKU": "Roku Inc.",
    "SHOP": "Shopify Inc.",
    "SPOT": "Spotify Technology",
    "SNOW": "Snowflake Inc.",
    "NET": "Cloudflare Inc.",
    "CRWD": "CrowdStrike Holdings",
    "DDOG": "Datadog Inc.",
    "MDB": "MongoDB Inc.",
    "ZS": "Zscaler Inc.",
    "PANW": "Palo Alto Networks",
}

US_EXCHANGE_TICKERS = list(COMMON_TICKERS.keys())


def search_tickers(query: str, limit: int = 20) -> list[dict]:
    """Search tickers by symbol or company name."""
    query_upper = query.upper()
    results = []
    for ticker, name in COMMON_TICKERS.items():
        if query_upper in ticker or query_upper in name.upper():
            results.append({"ticker": ticker, "name": name})
            if len(results) >= limit:
                break
    return results


def get_ticker_name(ticker: str) -> str | None:
    """Get company name for a ticker."""
    return COMMON_TICKERS.get(ticker.upper())
